# Generated by Django 4.2 on 2023-04-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('amount_type', models.CharField(choices=[('KG', 'Kilogram'), ('G', 'Gram'), ('RS', 'Regular Spoon'), ('TS', 'Tea Spoon'), ('L', 'Liter'), ('ML', 'Milliliter')], default='G', max_length=2)),
            ],
        ),
    ]
