# Generated by Django 4.2 on 2023-04-23 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_ingredient_amount_alter_recipe_duration_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='duration_type',
            field=models.CharField(choices=[('S', 'Second'), ('M', 'Minuets'), ('H', 'Hours')], default='S', max_length=1),
        ),
    ]
